config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'check_answers/correct'
  get 'check_answers/incorrect'
  get 'functions/main'
  get 'functions/zalgiris'
  get 'functions/atlanto'
  get 'functions/Jugoslavija'
  get 'functions/penktas'
  post 'check_answers/correct'
  post 'check_answers/incorrect'
  post 'functions/main'

  root 'functions#main'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/check_answers_controller.rb
class CheckAnswersController < ApplicationController
    def correct
        @text = "Teisingai"
    end
    
    def incorrect
        @text = "Neteisingai"
    end
end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
    before_action :fake_results, only: [:zalgiris, :atlanto, :Jugoslavija, :penktas, :main]

    def main
    end
  
    def zalgiris
      @result = "1999"
    end
  
    def atlanto
        @result = "1996"
    end
  
    def penktas
        @result = "1995"
    end
  
    def Jugoslavija
        @result = "2005"
    end
  
    def fake_results
      @resultFake1 = "1997"
      @resultFake2 = "1998"
      @resultFake3 = "1994"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_answers_helper.rb
module CheckAnswersHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/views/check_answers/correct.html.erb
<div class="correct_class_design">
<h1>Sveikinimai</h1>
<body>
<p><%= @text %></p>
<br>
<%= button_to "Atgal", functions_main_path, method: :post %>
</body>
</div>

app/views/check_answers/incorrect.html.erb
<div class="incorrect_class_design">
<h1>Blogai</h1>
<p><%= @text %></p>
<br>
<%= button_to "atgal", functions_main_path, method: :post %>
</div>

app/views/functions/Jugoslavija.html.erb
<div class="math_design">
<h1>Testas</h1>
<p>Pasirinkite teisinga atsakyma</p>
<p>Kelintais metais Europos cempionate Lietuviai pralaimejo finale Jugoslavijos komandai?</p>
<br>
<%= button_to @result, check_answers_correct_path, method: :post %>
<br>
<%= button_to @resultFake1, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake2, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake3, check_answers_incorrect_path, method: :post %>
</div>

app/views/functions/atlanto.html.erb
<div class="math_design">
<h1>Testas</h1>
<p>Pasirinkite teisinga atsakyma</p>
<p>Kelintais metais Lietuvos rinktine pralaimejo Serbijos komandai pusfinalyje Atlanto olimpiadoje?</p>
<br>
<%= button_to @result, check_answers_correct_path, method: :post %>
<br>
<%= button_to @resultFake1, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake2, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake3, check_answers_incorrect_path, method: :post %>
</div>

app/views/functions/main.html.erb
<div class="main_design">
<h1>Krepsinis</h1>
<p>Testas</p>
<br>
<%= link_to "Zalgiris", functions_zalgiris_path %>
<br>
<%= link_to "Lietuvos rinktine", functions_atlanto_path %>
<br>
<%= link_to "Europos cempionatas", functions_Jugoslavija_path %>
<br>
<%= link_to "Uzimta vieta", functions_penktas_path %>
</div>

app/views/functions/penktas.html.erb
<div class="math_design">
<h1>Testas</h1>
<p>Pasirinkite teisinga atsakyma</p>
<p>Kelintais metais Europos cempionate Lietuviai uzeme 5 vieta?</p>
<br>
<%= button_to @result, check_answers_correct_path, method: :post %>
<br>
<%= button_to @resultFake1, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake2, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake3, check_answers_incorrect_path, method: :post %>
</div>

app/views/functions/zalgiris.html.erb
<div class="math_design">
<h1>Testas</h1>
<p>Pasirinkite teisinga atsakyma</p>
<p>Kelintais metais Zalgiris laimejo eurolyga?</p>
<br>
<%= button_to @result, check_answers_correct_path, method: :post %>
<br>
<%= button_to @resultFake1, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake2, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake3, check_answers_incorrect_path, method: :post %>
</div>

app/views/functions/zalgiris2.html.erb
<div class="math_design">
<h1>Testas</h1>
<p>Pasirinkite teisinga atsakyma</p>
<p>Kelintais metais Zalgiris laimejo eurolyga?</p>
<br>
<%= button_to @result, check_answers_correct_path, method: :post %>
<br>
<%= button_to @resultFake1, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake2, check_answers_incorrect_path, method: :post %>
<br>
<%= button_to @resultFake3, check_answers_incorrect_path, method: :post %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>